# Below I have created model to predict article type

In [43]:
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from keras.models import Sequential, Model
from keras.layers import Conv2D, MaxPooling2D, Dense, Dropout, Flatten, Activation, GaussianNoise
from keras.layers import LeakyReLU
from keras.models import load_model
import tensorflow as tf
from sklearn.model_selection import train_test_split
import time
import datetime
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import os
from keras.models import Sequential
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestNeighbors

# Final.csv Contains all the changes i have done below in the code 

In [2]:
df = pd.read_csv('Final.csv',error_bad_lines=False)

# Editing Original Style.csv File and saving all the changes in Final.csv. 

In [5]:
options = ['Apparel', 'Accessories', 'Footwear'] 
  
# selecting rows based on condition 
final = df.loc[df['masterCategory'].isin(options)] 

In [6]:
final.masterCategory.value_counts()

Apparel        21397
Accessories    11274
Footwear        9219
Name: masterCategory, dtype: int64

In [8]:
final.to_csv('Editted.csv')

In [9]:
df.masterCategory.value_counts()

Apparel           21397
Accessories       11274
Footwear           9219
Personal Care      2403
Free Items          105
Sporting Goods       25
Home                  1
Name: masterCategory, dtype: int64

In [10]:
options = ['Personal Care', 'Free Items', 'Sporting Goods', 'Home']

temp = df.loc[df['masterCategory'].isin(options)]

temp.masterCategory.value_counts()

Personal Care     2403
Free Items         105
Sporting Goods      25
Home                 1
Name: masterCategory, dtype: int64

In [11]:
temp.sort_values(by = 'id')

id  gender  masterCategory       subCategory articleType baseColour  \
35931   1550  Unisex  Sporting Goods  Sports Equipment   Footballs      White   
37741   1551  Unisex  Sporting Goods  Sports Equipment   Footballs     Orange   
14507   1552  Unisex  Sporting Goods  Sports Equipment   Footballs      White   
11915   1553  Unisex  Sporting Goods  Sports Equipment   Footballs      White   
42801   1626  Unisex  Sporting Goods  Sports Equipment   Footballs       Blue   
...      ...     ...             ...               ...         ...        ...   
29888  59949   Women   Personal Care         Fragrance   Deodorant     Orange   
15747  59950   Women   Personal Care         Fragrance   Deodorant     Yellow   
13233  59951   Women   Personal Care         Fragrance   Deodorant       Blue   
16355  59961     Men   Personal Care         Fragrance   Deodorant      Green   
36801  59962     Men   Personal Care         Fragrance   Deodorant       Gold   

       season    year   usage                         productDisplayName  
35931    Fall  2010.0  Sports              Puma Cat Trainer-WBL Football  
37741    Fall  2010.0  Sports         Puma Power Cat Trainer-OB Football  
14507    Fall  2010.0  Sports         Puma Power Cat Trainer-WR Football  
11915    Fall  2010.0  Sports        Puma Power Cat Hard Ground Football  
42801  Summer  2011.0  Sports       Kipsta F300 Football Size 5 Football  
...       ...     ...     ...                                        ...  
29888  Spring  2017.0  Casual          Taylor of London Women Hawaii Deo  
15747  Spring  2017.0  Casual         Taylor of London Women Kashmir Deo  
13233  Spring  2017.0  Casual  Taylor of London Lace Perfumed Body Spray  
16355  Spring  2017.0  Casual                         Denim Men Sync Deo  
36801  Spring  2017.0  Casual                         Denim Men Vibe Deo  

[2534 rows x 10 columns]

In [12]:
label  = temp['id']

In [13]:
label= label.tolist()

In [14]:
label.sort()

In [17]:
len(label)

2534

In [16]:
len(label)

2534

In [37]:
os.getcwd()

'C:\\Users\\dell\\OneDrive\\Recoomendation System\\images'

In [19]:
os.chdir('images/')

In [20]:
for i in range(0, len(label)):
    delete = str(label[i]) + '.jpg'
    os.remove(delete)

In [21]:
len(final)

41890

In [22]:
final.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName  
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt  
1  2012.0  Casual             Peter England Men Party Blue Jeans  
2  2016.0  Casual                       Titan Women Silver Watch  
3  2011.0  Casual  Manchester United Men Solid Black Track Pants  
4  2012.0  Casual                          Puma Men Grey T-shirt

In [23]:
label  = final['id']

In [50]:
temp = final.articleType.value_counts()


In [51]:
temp

Tshirts                  7067
Shirts                   3217
Casual Shoes             2845
Watches                  2542
Sports Shoes             2036
                         ... 
Rain Trousers               2
Hair Accessory              1
Perfume and Body Mist       1
Suits                       1
Shoe Laces                  1
Name: articleType, Length: 108, dtype: int64

In [52]:
dropList = []
for i in range(len(temp)):
    if(temp[i] >50):
        dropList.append(temp.index[i])

In [53]:
dropList

['Tshirts',
 'Shirts',
 'Casual Shoes',
 'Watches',
 'Sports Shoes',
 'Kurtas',
 'Tops',
 'Handbags',
 'Heels',
 'Sunglasses',
 'Wallets',
 'Flip Flops',
 'Sandals',
 'Briefs',
 'Belts',
 'Backpacks',
 'Socks',
 'Formal Shoes',
 'Jeans',
 'Shorts',
 'Trousers',
 'Flats',
 'Bra',
 'Dresses',
 'Sarees',
 'Earrings',
 'Track Pants',
 'Clutches',
 'Sweatshirts',
 'Caps',
 'Sweaters',
 'Ties',
 'Jackets',
 'Innerwear Vests',
 'Kurtis',
 'Tunics',
 'Nightdress',
 'Leggings',
 'Pendant',
 'Capris',
 'Necklace and Chains',
 'Night suits',
 'Trunk',
 'Skirts',
 'Ring',
 'Scarves',
 'Dupatta',
 'Cufflinks',
 'Accessory Gift Set',
 'Kurta Sets',
 'Stoles',
 'Duffel Bag',
 'Bangle',
 'Laptop Bag',
 'Sports Sandals',
 'Bracelet',
 'Lounge Pants',
 'Jewellery Set',
 'Boxers']

In [54]:
temp = final.loc[final['articleType'].isin(dropList)]

temp.articleType.value_counts()

Tshirts                7067
Shirts                 3217
Casual Shoes           2845
Watches                2542
Sports Shoes           2036
Kurtas                 1844
Tops                   1762
Handbags               1757
Heels                  1323
Sunglasses             1073
Wallets                 935
Flip Flops              914
Sandals                 897
Briefs                  849
Belts                   813
Backpacks               722
Socks                   686
Formal Shoes            637
Jeans                   609
Shorts                  547
Trousers                530
Flats                   500
Bra                     477
Dresses                 464
Sarees                  427
Earrings                416
Track Pants             304
Clutches                289
Sweatshirts             285
Caps                    283
Sweaters                277
Ties                    258
Jackets                 258
Innerwear Vests         242
Kurtis                  234
Tunics              

In [55]:
temp.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName  
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt  
1  2012.0  Casual             Peter England Men Party Blue Jeans  
2  2016.0  Casual                       Titan Women Silver Watch  
3  2011.0  Casual  Manchester United Men Solid Black Track Pants  
4  2012.0  Casual                          Puma Men Grey T-shirt

In [41]:
label  = temp['id']

In [42]:
label= label.tolist()

In [43]:
label.sort()

In [44]:
len(label)

758

In [47]:
for i in range(72, len(label)):
    delete = str(label[i]) + '.jpg'
    os.remove(delete)

In [46]:
i

71

In [56]:
len(temp)

41131

In [57]:
temp.to_csv('Final.csv')

In [8]:
os.getcwd()

'C:\\Users\\dell\\OneDrive\\Recoomendation System'

In [62]:
os.chdir('C:\\Users\\dell\\OneDrive\\Recoomendation System\\')

In [18]:
df= pd.read_csv('Final.csv')

In [27]:
df.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName      files  
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt  15970.jpg  
1  2012.0  Casual             Peter England Men Party Blue Jeans  39386.jpg  
2  2016.0  Casual                       Titan Women Silver Watch  59263.jpg  
3  2011.0  Casual  Manchester United Men Solid Black Track Pants  21379.jpg  
4  2012.0  Casual                          Puma Men Grey T-shirt  53759.jpg

In [20]:
df.describe()

Unnamed: 0            id          year
count  41131.000000  41131.000000  41130.000000
mean   22219.797282  28487.216309   2012.557987
std    12813.096571  16675.167347      1.923190
min        0.000000   1163.000000   2007.000000
25%    11107.500000  13877.500000   2011.000000
50%    22215.000000  27424.000000   2012.000000
75%    33314.500000  42670.500000   2013.000000
max    44423.000000  60000.000000   2018.000000

In [158]:
df.drop('Unnamed: 0', inplace = True, axis = 1)

In [178]:
df['files'] = df.apply(lambda temp: str(temp.id) + '.jpg', axis = 1)

In [180]:
df.to_csv('Final.csv')

In [232]:
df.head()

id gender masterCategory subCategory  articleType baseColour  season  \
0  15970    Men        Apparel     Topwear       Shirts  Navy Blue    Fall   
1  39386    Men        Apparel  Bottomwear        Jeans       Blue  Summer   
2  59263  Women    Accessories     Watches      Watches     Silver  Winter   
3  21379    Men        Apparel  Bottomwear  Track Pants      Black    Fall   
4  53759    Men        Apparel     Topwear      Tshirts       Grey  Summer   

     year   usage                             productDisplayName      files  
0  2011.0  Casual               Turtle Check Men Navy Blue Shirt  15970.jpg  
1  2012.0  Casual             Peter England Men Party Blue Jeans  39386.jpg  
2  2016.0  Casual                       Titan Women Silver Watch  59263.jpg  
3  2011.0  Casual  Manchester United Men Solid Black Track Pants  21379.jpg  
4  2012.0  Casual                          Puma Men Grey T-shirt  53759.jpg

# Using article type column and built a cnn network to predict article

In [3]:
X = df['files']
y= df['articleType']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                            zoom_range = 0.3
                            )

In [6]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [7]:
X = pd.concat([X_train, y_train], axis=1)

In [11]:
test = pd.concat([X_test, y_test], axis=1)

In [12]:
X = X.reset_index()
X.drop(['index'], axis = 1, inplace = True)
X.head()

files   articleType
0  21987.jpg      Handbags
1   6755.jpg  Sports Shoes
2  35684.jpg  Casual Shoes
3  19098.jpg        Kurtas
4  19431.jpg        Shorts

In [13]:
test = test.reset_index()
test.drop(['index'], axis =1, inplace = True)
test.head()

files   articleType
0   5409.jpg  Sports Shoes
1  58340.jpg    Flip Flops
2  58466.jpg         Belts
3  42068.jpg       Wallets
4  20398.jpg      Handbags

In [14]:
train_data = train_datagen.flow_from_dataframe(dataframe=X, directory='images/',x_col = 'files', y_col = 'articleType', target_size = (64,64))

Found 27555 validated image filenames belonging to 59 classes.


In [15]:
test_data = test_datagen.flow_from_dataframe(dataframe=test, directory='images/',x_col = 'files', y_col = 'articleType', target_size = (64,64))

Found 13572 validated image filenames belonging to 59 classes.


In [32]:
cnn = Sequential()

In [33]:
cnn.add(Conv2D(filters = 16, kernel_size = (3,3) ,strides = (1,1),padding = "same", input_shape = (64,64,3), activation = 'relu'))
cnn.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
cnn.add(GaussianNoise(0.1))
cnn.add(Conv2D(filters = 32, kernel_size = (3,3), strides = (1,1), padding="same", input_shape = (32,32,16), activation = 'relu'))
cnn.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
cnn.add(Flatten())
cnn.add(Dense(120, activation = 'relu'))
cnn.add(Dropout(0.5))
cnn.add(Dense(59, activation = 'softmax'))


In [18]:
cnn.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [95]:
cnn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 64, 64, 16)        448       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 32, 32, 16)        0         
_________________________________________________________________
gaussian_noise_2 (GaussianNo (None, 32, 32, 16)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 32, 32, 32)        4640      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 120)              

In [21]:
start = time.time()
cnn.fit_generator(
    train_data,
    epochs=9,
    validation_data=test_data,
)
end = time.time()
print('Processing time:',(end - start)/60)

Epoch 1/9
862/862 [==============================] - 296s 344ms/step - loss: 0.0563 - accuracy: 0.9845 - val_loss: 0.0262 - val_accuracy: 0.9882
Epoch 2/9
862/862 [==============================] - 289s 335ms/step - loss: 0.0426 - accuracy: 0.9868 - val_loss: 0.0430 - val_accuracy: 0.9900
Epoch 3/9
862/862 [==============================] - 295s 343ms/step - loss: 0.0384 - accuracy: 0.9879 - val_loss: 0.0239 - val_accuracy: 0.9907
Epoch 4/9
862/862 [==============================] - 290s 337ms/step - loss: 0.0359 - accuracy: 0.9884 - val_loss: 0.0277 - val_accuracy: 0.9910
Epoch 5/9
862/862 [==============================] - 293s 340ms/step - loss: 0.0342 - accuracy: 0.9890 - val_loss: 0.0229 - val_accuracy: 0.9908
Epoch 6/9
862/862 [==============================] - 289s 336ms/step - loss: 0.0334 - accuracy: 0.9892 - val_loss: 0.0268 - val_accuracy: 0.9914
Epoch 7/9
862/862 [==============================] - 284s 330ms/step - loss: 0.0330 - accuracy: 0.9893 - val_loss: 0.0329 - val_ac

In [23]:
cnn.save('keras_model.h5')

In [22]:
model = load_model('keras_model.h5')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 64, 64, 16)        448       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 32, 16)        0         
_________________________________________________________________
gaussian_noise_1 (GaussianNo (None, 32, 32, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 120)              

# Prediction using predict_generator function. 

In [21]:
true_classes = test_data.classes
class_labels = list(test_data.class_indices.keys())   

In [22]:
test_steps_per_epoch = np.math.ceil(test_data.samples / test_data.batch_size)


In [26]:
predictions = model.predict_generator(test_data, steps=test_steps_per_epoch)

In [27]:
predicted_classes = np.argmax(predictions, axis=1)

In [28]:
confusion = confusion_matrix(true_classes, predicted_classes)
print(confusion)

[[ 0  1  0 ...  0  1  2]
 [ 1  8  0 ...  0  3 11]
 [ 0  0  0 ...  0  0  1]
 ...
 [ 0  3  0 ...  0  2  5]
 [ 1  8  0 ...  0 12 16]
 [ 3 13  0 ...  0 18 54]]


In [30]:
accuracy_score(true_classes, predicted_classes)

0.0623342175066313

# Evaluating the above model

In [23]:
model_evaluate=model.evaluate_generator(generator=test_data)

In [24]:
print('Test loss:', model_evaluate[0])
print('Test accuracy:', model_evaluate[1])

Test loss: 0.016110751777887344
Test accuracy: 0.9918904304504395


# Feauture extraction from dropout_1 layer. The layer above softmax

In [26]:
intermediate_layer_model = Model(inputs=model.input,outputs=model.get_layer('dropout_1').output)
intermediate_layer_model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1_input (InputLayer)  (None, 64, 64, 3)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 64, 64, 16)        448       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 32, 16)        0         
_________________________________________________________________
gaussian_noise_1 (GaussianNo (None, 32, 32, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 32, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 8192)              0   

In [27]:
feauture_engg_data = intermediate_layer_model.predict(train_data)
feauture_engg_data = pd.DataFrame(feauture_engg_data)

In [28]:
feauture_test = intermediate_layer_model.predict(test_data)
feauture_test = pd.DataFrame(feauture_test)

In [19]:
feauture_engg_data.to_csv('feauture_engg_data_inital.csv')
feauture_test.to_csv('feauture_test_initial.csv')

In [17]:
feauture_engg_data = pd.read_csv('feauture_engg_data_inital.csv')
feauture_test = pd.read_csv('feauture_test_initial.csv')

In [18]:
feauture_engg_data = pd.concat([X, feauture_engg_data], axis = 1)
feauture_test = pd.concat([test, feauture_test], axis = 1)

# Trying another model to predict article type

In [44]:
temp = Sequential()

In [45]:
temp.add(Conv2D(filters = 32, kernel_size = (3,3) ,strides = (1,1),padding = "same", input_shape = (64,64,3), activation = 'relu'))
temp.add(LeakyReLU(alpha=0.05))
temp.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
temp.add(Dropout(0.2))
temp.add(Conv2D(filters = 32, kernel_size = (3,3), strides = (1,1), padding="same", input_shape = (32,32,16), activation = 'relu'))
temp.add(LeakyReLU(alpha=0.05))
temp.add(MaxPooling2D(pool_size = (2,2), strides = (2,2)))
temp.add(Dropout(0.2))
temp.add(Flatten())
temp.add(Dense(120, activation = 'relu'))
temp.add(LeakyReLU(alpha=0.05))
temp.add(Dropout(0.5))
temp.add(Dense(59, activation = 'softmax'))


In [46]:
temp.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 64, 64, 32)        896       
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 64, 64, 32)        0         
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 32, 32, 32)        0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 32, 32, 32)        9248      
_________________________________________________________________
leaky_re_lu_2 (LeakyReLU)    (None, 32, 32, 32)        0         
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 16, 16, 32)       

In [48]:
temp.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [49]:
start = time.time()
temp.fit_generator(
    train_data,
    epochs=9,
    validation_data=test_data,
)
end = time.time()
print('Processing time:',(end - start)/60)

Epoch 1/9
862/862 [==============================] - 854s 991ms/step - loss: 0.0567 - accuracy: 0.9846 - val_loss: 0.0122 - val_accuracy: 0.9890
Epoch 2/9
862/862 [==============================] - 393s 456ms/step - loss: 0.0404 - accuracy: 0.9874 - val_loss: 0.0359 - val_accuracy: 0.9908
Epoch 3/9
862/862 [==============================] - 368s 427ms/step - loss: 0.0360 - accuracy: 0.9886 - val_loss: 0.0145 - val_accuracy: 0.9910
Epoch 4/9
862/862 [==============================] - 358s 415ms/step - loss: 0.0338 - accuracy: 0.9892 - val_loss: 0.0116 - val_accuracy: 0.9918
Epoch 5/9
862/862 [==============================] - 362s 420ms/step - loss: 0.0330 - accuracy: 0.9895 - val_loss: 0.0231 - val_accuracy: 0.9916
Epoch 6/9
862/862 [==============================] - 368s 427ms/step - loss: 0.0325 - accuracy: 0.9896 - val_loss: 0.0235 - val_accuracy: 0.9919
Epoch 7/9
862/862 [==============================] - 366s 424ms/step - loss: 0.0324 - accuracy: 0.9897 - val_loss: 0.0234 - val_ac

In [50]:
predictions = temp.predict_generator(test_data, steps=test_steps_per_epoch)

In [51]:
predicted_classes = np.argmax(predictions, axis=1)

In [52]:
accuracy_score(true_classes, predicted_classes)

0.06395520188623637